spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ekorxona
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  access_expiry: 300000  # 5 minutes (5 minutes * 60 seconds/minute)
  refresh_expiry: 86400000  # 1 day (60 seconds/minute * 60 minutes/hour * 24 hours/day)
  secret: gjhkoiutrefdsavzbxcnmktjyhretgwedfvbnjkrjyerhsfg